[general]
run_mode = "all"
fetch_limit = 100
polling_interval = 5
polling_timeout = 240

[mail]
login = "ME@GMAIL.COM"
password = "XXXX XXXX XXXX XXXX"
host = "imap.gmail.com"
port = 993

[[scripts]]
name = "example 1"
mode = "history"
exec_once = true
exec_path = "python3 /Users/USER/some_script.py --debug"
regexp_main = "Google"
regexp_main_target = "title"

[[scripts]]
name = "example 2"
mode = "polling"
exec_once = false
exec_path = "node /Users/USER/test.js"
regexp_from = "noreply@steampowered.com"
regexp_main = "Sold"
regexp_main_target = "title"