[general]
mode = "history"
fetch_limit = 30
polling_interval = 3

[mail]
host = "imap.gmail.com"
port = 993

[[scripts]]
name = "sec"
exec_once = true
exec_path = "python3 /Users/USER/some_script.py --debug"
regexp_main = "Google"
regexp_main_target = "title"

[[scripts]]
name = "steam"
exec_once = false
exec_path = "node /Users/USER/test.js"
regexp_from = "noreply@steampowered.com"
regexp_main = "Sold"
regexp_main_target = "title"