[general]
fetch_full = 500
fetch_recent = 50

[mail]
host = "imap.gmail.com"
port = 993

[[scripts]]
name = "sec"
exec_once = true
exec_path = "/Users/user/some_script.py"
regexp = "Google"

[[scripts]]
name = "steam"
exec_once = false
exec_path = "..."
regexp = "Steam"
regexp_target = "title" # Optional, default = "title"
python_ver = 2 # Optional, default = 3