[general]
fetch_full = 500
fetch_recent = 50

[mail]
host = "imap.gmail.com"
port = 993

[[handlers]]
name = "sec"
pattern = "Google"
exec_once = true
python_ver = 3

[[handlers]]
name = "steam"
pattern = "Steam"
exec_once = false
python_ver = 2