[general]
fetch_full = 500
fetch_recent = 50

[mail]
host = "imap.gmail.com"
port = 993

[[handlers]]
name = "sec"
exec_once = true
exec_path = "/Users/user/some_script.py"
pattern = "Google"

[[handlers]]
name = "steam"
exec_once = false
exec_path = "..."
pattern = "Steam"
pattern_type = "title" # Optional, default = "title"
python_ver = 2 # Optional, default = 3